server.port=8080
spring.application.name=bff-service

spring.datasource.url=jdbc:postgresql://${RDS_HOST}:${RDS_PORT}/${BFF_DB_NAME:bff_db}
spring.datasource.username=${RDS_USERNAME}
spring.datasource.password=${RDS_PASSWORD}
spring.jpa.hibernate.ddl-auto=update

spring.rabbitmq.addresses=${RABBITMQ_URL}
rabbitmq.system.exchange.name=${RABBITMQ_EXCHANGE}
rabbitmq.bff.queue.name=bff.events.queue

jwt.secret=${JWT_SECRET}
#2h
jwt.expiration=7200000
jwt.inactivity-limit-ms=${JWT_INACTIVITY_LIMIT_MS:7200000}
#5m
jwt.refresh-before-expiry-ms=${JWT_REFRESH_BEFORE_EXPIRY_MS:300000}

app.cors.allowed-origins=${CORS_ALLOWED_ORIGINS:http://localhost:4200}

services.order-gateway.url=${ORDER_GATEWAY_URL:http://localhost:8081}
services.packing.url=${PACKING_SERVICE_URL:http://localhost:8082}
services.picking.url=${PICKING_SERVICE_URL:http://localhost:8083}
services.reservation.url=${RESERVATION_SERVICE_URL:http://localhost:8084}
services.shipping.url=${SHIPPING_SERVICE_URL:http://localhost:8085}

spring.cloud.openfeign.circuitbreaker.enabled=true
spring.autoconfigure.exclude=org.springframework.cloud.autoconfigure.LifecycleMvcEndpointAutoConfiguration

# Retry does not retry when circuit breaker is open
resilience4j.retry.configs.default.ignore-exceptions=io.github.resilience4j.circuitbreaker.CallNotPermittedException