server.port=8081
spring.application.name=order-gateway-service

spring.datasource.url=jdbc:postgresql://localhost:5433/${POSTGRES_DB}?currentSchema=order_schema
spring.datasource.username=${POSTGRES_USER}
spring.datasource.password=${POSTGRES_PASSWORD}
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.default_schema=order_schema

spring.rabbitmq.addresses=${RABBITMQ_URL}

rabbitmq.system.exchange.name=${RABBITMQ_EXCHANGE}