apiVersion: v1
kind: Secret
metadata:
  name: outbound-secret
  namespace: default
type: Opaque
stringData:
  RDS_USERNAME: "postgres"
  RDS_PASSWORD: "password"

  AWS_ACCESS_KEY_ID: ""
  AWS_SECRET_ACCESS_KEY: ""
  AWS_SESSION_TOKEN: ""
