apiVersion: v1
kind: ConfigMap
metadata:
  name: outbound-configmap
  namespace: default
data:
  RDS_HOST: "outbound-system-rds.c55wscpuxpvv.us-east-1.rds.amazonaws.com"
  RDS_PORT: "5432"
  RABBITMQ_URL: "amqps://slgoqcfb:pAeZss0Xi_CFNwmsUWASxFJYwwpsL9xr@cow.rmq2.cloudamqp.com/slgoqcfb"
  RABBITMQ_EXCHANGE: "outbound.exchange"

  AWS_REGION: "us-east-1"
  AWS_BUCKET_NAME: "pwr-cloud-lab-project-2026"

  ORDER_DB_NAME: "order_db"
  PACKING_DB_NAME: "packing_db"
  RESERVATION_DB_NAME: "reservation_db"