apiVersion: v1
kind: ConfigMap
metadata:
  name: outbound-configmap
data:
  RDS_HOST: "outbound-system-rds.c55wscpuxpvv.us-east-1.rds.amazonaws.com"
  RDS_PORT: "5432"
  RABBITMQ_URL: "amqps://slgoqcfb:pAeZss0Xi_CFNwmsUWASxFJYwwpsL9xr@cow.rmq2.cloudamqp.com/slgoqcfb"
  RABBITMQ_EXCHANGE: "outbound.exchange"

  AWS_REGION: "us-east-1"
  AWS_BUCKET_NAME: "pwr-cloud-lab-project-2026"

  ORDER_DB_NAME: "order_db"
  PACKING_DB_NAME: "packing_db"
  RESERVATION_DB_NAME: "reservation_db"

---
apiVersion: v1
kind: Secret
metadata:
  name: outbound-secret
type: Opaque
stringData:
  RDS_USERNAME: "postgres"
  RDS_PASSWORD: "password"

  AWS_ACCESS_KEY_ID: ""
  AWS_SECRET_ACCESS_KEY: ""
  AWS_SESSION_TOKEN: ""
