apiVersion: apps/v1
kind: Deployment
metadata:
  name: order-service-deployment
  namespace: default
  labels:
    app: order-service
spec:
  replicas: 4

  selector:
    matchLabels:
      app: order-service

  template:
    metadata:
      labels:
        app: order-service

    spec:
      restartPolicy: Always
      containers:
        - name: order-service
          image: mateuszplaska/order-service:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 8081
          resources:
            requests:
              memory: "512Mi"
              cpu: "500m"
            limits:
              memory: "1Gi"
              cpu: "1"
          envFrom:
            - configMapRef:
                name: outbound-configmap
            - secretRef:
                name: outbound-secret