apiVersion: v1
kind: Service
metadata:
  name: packing-service
  namespace: default
  labels:
    app: packing-service
spec:
  type: LoadBalancer
  selector:
    app: packing-service
  ports:
    - protocol: TCP
      port: 8082
      targetPort: 8082