apiVersion: v1
kind: Service
metadata:
  name: picking-service
  namespace: default
  labels:
    app: picking-service
spec:
  type: LoadBalancer
  selector:
    app: picking-service
  ports:
    - protocol: TCP
      port: 8083
      targetPort: 8083