apiVersion: apps/v1
kind: Deployment
metadata:
  name: reservation-service-deployment
  namespace: default
  labels:
    app: reservation-service
spec:
  replicas: 3

  selector:
    matchLabels:
      app: reservation-service

  template:
    metadata:
      labels:
        app: reservation-service

    spec:
      restartPolicy: Always
      containers:
        - name: reservation-service
          image: mateuszplaska/reservation-service:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 8084
          resources:
            requests:
              memory: "256Mi"
              cpu: "250m"
            limits:
              memory: "768Mi"
              cpu: "750m"
          envFrom:
            - configMapRef:
                name: outbound-configmap
            - secretRef:
                name: outbound-secret