apiVersion: apps/v1
kind: Deployment
metadata:
  name: reservation-service-deployment
  namespace: default
  labels:
    app: reservation-service
spec:
  replicas: 2

  selector:
    matchLabels:
      app: reservation-service

  template:
    metadata:
      labels:
        app: reservation-service

    spec:
      restartPolicy: Always
      containers:
        - name: reservation-service
          image: mateuszplaska/reservation-service:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 8084
          resources:
            requests:
              memory: "256Mi"
              cpu: "100m"
            limits:
              memory: "512Mi"
              cpu: "500m"
          envFrom:
            - configMapRef:
                name: outbound-configmap
            - secretRef:
                name: outbound-secret