server.port=8083
spring.application.name=picking-service

spring.mongodb.uri=mongodb://${MONGO_INITDB_ROOT_USERNAME}:${MONGO_INITDB_ROOT_PASSWORD}@localhost:27017/picking_db?authSource=admin

spring.rabbitmq.addresses=${RABBITMQ_URL}