server.port=8085
spring.application.name=shipping-service

aws.region=${AWS_REGION}
aws.access-key=${AWS_ACCESS_KEY_ID}
aws.secret-key=${AWS_SECRET_ACCESS_KEY}
aws.session-token=${AWS_SESSION_TOKEN}

aws.dynamodb.shipping-table=shipments

spring.rabbitmq.addresses=${RABBITMQ_URL}
rabbitmq.system.exchange.name=${RABBITMQ_EXCHANGE}
rabbitmq.shipping.queue.name=shipping.queue