services:
  order-service:
    image: mateuszplaska/order-service:latest
    build:
      context: .
      dockerfile: order-gateway-service/Dockerfile
    ports:
      - "8081:8081"
    env_file: .env
    networks:
      - outbound-net

  packing-service:
    image: mateuszplaska/packing-service:latest
    build:
      context: .
      dockerfile: packing-service/Dockerfile
    ports:
      - "8082:8082"
    env_file: .env
    networks:
      - outbound-net

  picking-service:
    image: mateuszplaska/picking-service:latest
    build:
      context: .
      dockerfile: picking-service/Dockerfile
    ports:
      - "8083:8083"
    env_file: .env
    networks:
      - outbound-net

  reservation-service:
    image: mateuszplaska/reservation-service:latest
    build:
      context: .
      dockerfile: reservation-service/Dockerfile
    ports:
      - "8084:8084"
    env_file: .env
    networks:
      - outbound-net

  shipping-service:
    image: mateuszplaska/shipping-service:latest
    build:
      context: .
      dockerfile: shipping-service/Dockerfile
    ports:
      - "8085:8085"
    env_file: .env
    networks:
      - outbound-net

networks:
  outbound-net:
    driver: bridge